#!/usr/bin/env bash
# This script pings an IP address passed as an argument

# Check if argument is provided
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Ping the provided IP address 5 times
ping -c 5 "$1"

# ping uses ICMP (Internet Control Message Protocol) to send small packets(called echo requests) to another device one the is_the_host_on_the_network
# if the device is reachable, it responds with an echo reply
